### ISSUE TITLE
Autoconnect to VPN fails at system start if "Store password only for this user" is set

### ISSUE THREAD

**Issue by YaLTeR** [fedora-silverblue/issue-tracker#144]
If I add a VPN with "Store password only for this user" and make it autoconnect for my Ethernet connection (via `nm-connection-editor` (currently broken) or by adding it to `connection.secondaries` in `nmcli`), then the connection fails to activate on system start (so when I log in I have no internet and have to toggle it manually).

The log says:

```
апр 02 11:29:33 autumnblaze NetworkManager[965]: <error> [1617352173.5080] vpn-connection[0x55e3f70ba0e0,bb713cd7-5b2f-4a93-8b01-a5cc77fb717c,"Mullvad",0]: Failed to request VPN secrets #3: No agents were available for this request.
апр 02 11:29:33 autumnblaze NetworkManager[965]: <info>  [1617352173.5082] device (enp14s0): state change: secondaries -> failed (reason 'secondary-connection-failed', sys-iface-state: 'managed')
апр 02 11:29:33 autumnblaze NetworkManager[965]: <info>  [1617352173.5086] manager: NetworkManager state is now DISCONNECTED
апр 02 11:29:33 autumnblaze NetworkManager[965]: <warn>  [1617352173.5091] device (enp14s0): Activation: failed for connection 'enp14s0'
```

Changing the option to "Store password for all users" fixes the problem.

```
State: idle
BootedDeployment:
● ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210401.n.0 (2021-04-01T08:05:16Z)
                BaseCommit: 49ff64e67fd02d75339ed0c121f55032cc21918ae0e484ce60967a5732aa2b09
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
       RemovedBasePackages: firefox 87.0-2.fc34
      ReplacedBasePackages: mutter 40.0-4.fc34 -> 40.0-1.1.fc34
           LayeredPackages: alacritty bcache-tools exa fish gdb gnome-boxes gnome-tweaks
                            neovim sysprof wl-clipboard
             LocalPackages: edid-asus-1-1.fc34.noarch
                 Initramfs: -i /etc/initramfs-overlay /
```
