### ISSUE TITLE
[BUG] If the network is temporarily shut down during the Receiving objects stage of the rpm-ostree upgrade, the upgrade will not resume after the network is restored.

### ISSUE THREAD

**Issue by mikunimaru** [fedora-silverblue/issue-tracker#179]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
If the network is temporarily shut down during the Receiving objects stage of the rpm-ostree upgrade, the upgrade will not resume after the network is restored.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1.rpm-ostree upgrade
2.Temporarily disconnects the network at the Receiving objects stage.

**Expected behavior**
Resume after network recovery.

**Screenshots**
![Screenshot from 2021-07-06 11-50-29](https://user-images.githubusercontent.com/43168745/124535827-cb551480-de51-11eb-8c9c-b969907f9c79.png)

**OS version:**
```
State: busy
Transaction: upgrade 
  Initiator: client(id:cli dbus:1.177 unit:vte-spawn-c8c40f25-35a3-4693-9fdd-ae0c2a4ccf78.scope uid:1000)
BootedDeployment:
● ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210423.n.0 (2021-04-23T08:10:25Z)
                BaseCommit: 7b99463136830fd9b18f8daf5f7973f3e15eaa3532f8dbcbb4f7eb9673170461
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: fcitx5-configtool fcitx5-mozc java-1.8.0-openjdk-devel pam_mount
                            plymouth-theme-solar vim zsh
             LocalPackages: rpmfusion-free-release-34-1.noarch
                            rpmfusion-nonfree-release-34-0.1.noarch
                 Initramfs: regenerate
```
