### ISSUE TITLE
[BUG] rpm-ostree kargs --editor stopped working on F35

### ISSUE THREAD

**Issue by JayDoubleu** [fedora-silverblue/issue-tracker#217]
**Describe the bug**
Using `rpm-ostree kargs --editor `  returns                  
`No changes.` even when changes have been made.

While when there are no changes made it correctly returns: 
```shell
rpm-ostree kargs --editor
error: The kernel arguments remained the same

```

**OS version:**
```
rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/35/x86_64/silverblue
                   Version: 35.20211024.n.0 (2021-10-24T07:58:05Z)
                BaseCommit: c642c4729c030de38b2f3f0c3f251cf1d1aff5bf642c82aab7678b13affed0d0
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
           LayeredPackages: wireshark xorg-x11-drv-nvidia-cuda 'gcc-c++' util-linux-user solaar xorg-x11-drv-nvidia python3-pip terminator gnome-tweaks arandr lm_sensors tcpdump nmap dlib-devel tmux zsh
                            gnome-firmware python3-devel cmake akmod-nvidia poetry
             LocalPackages: opera-stable-80.0.4170.16-0.x86_64
```
