### ISSUE TITLE
[Request] Remove GNOME Tour from base image 

### ISSUE THREAD

**Issue by A6GibKm** [fedora-silverblue/issue-tracker#252]
Given that one can use a Flatpak from the `fedora` repository and have it preinstalled on new installs, one can consider removing it from the base image.

**Comment by tpopela** [comment]
This is definitely a valid request, but there isn't a GNOME Tour Fedora Flatpak yet - I will try to create it in the next few weeks (or actually contributions are welcome) when I will work on Fedora 36 Flatpak Runtime.

**Comment by bobslept** [comment]
Hi there. In order to help out I've tried to create a flatpak of gnome-tour. It's my first flatpak but it worked out. Currently it's made on  Fedora 35. But I would think that changing it to Fedora 36 would be rather easy by replacing the [f35] with [f36], when the runtime is ready.

After building and installing it, I was able to run it with `flatpak run org.gnome.Tour` and it worked perfect.
Please let me know if I can help and which steps to take from here.

-- Bob

**gnome-tour.yaml**
```
---
document: modulemd
version: 2
data:
  summary: GNOME Tour and Greeter
  description: A guided tour and greeter for GNOME.
  license:
    module:
    - GPLv3+
    - CC-BY-SA
  dependencies:
  - buildrequires:
      flatpak-common: [f35]
      flatpak-runtime: [f35]
      platform: [f35]
    requires:
      flatpak-common: [f35]
      flatpak-runtime: [f35]
      platform: [f35]
  profiles:
    default:
      rpms:
      - gnome-tour
  components:
    rpms:
      gnome-tour:
        rationale: Application package
        ref: f35
...
```

**container.yaml**
```
compose:
    modules:
    - gnome-tour:master
flatpak:
    id: org.gnome.Tour
    branch: master
    command: gnome-tour
    finish-args: |-
        --share=ipc
        --socket=x11
        --socket=wayland
        --device=dri
```
