### ISSUE TITLE
[BUG] Fedora 36 - Openconnect csd-post gives empty document and indefinitely connects

### ISSUE THREAD

**Issue by Meister1593** [fedora-silverblue/issue-tracker#274]
**Describe the bug**
Openconnect csd post wrapper used for anyconnect vpn service fails unexpectedly with empty document returned from vpn.

**To Reproduce**
I'm not sure if it's possible to replicate locally (requires vpn credentials) but i will at least try to replicate it the way i did

1. Install Silverblue 36
2. In terminal - `sudo openconnect --user=user --csd-wrapper=/usr/libexec/openconnect/csd-post.sh hostname`
3. It will repeatedly try to connect and never actually establish vpn connection. It will also output 
```
-:1.1: Document is empty

^
-:1.1: Document is empty

^
``` 
while trying to connect (only once)
**Expected behavior**
Openconnect has to establish connection and give login form to proceed further

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220508.0 (2022-05-08T00:42:01Z)
                BaseCommit: dd4ac38b4030e0192777eef2c243f1b2a777f6d6526fd52b84f0a2ec2984b6bb
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
       RemovedBasePackages: firefox 100.0-2.fc36 gnome-software gnome-software-rpm-ostree 42.0-4.fc36 vim-minimal 2:8.2.4845-1.fc36
           LayeredPackages: corectrl distrobox fish fzf gnome-tweaks google-roboto-fonts langpacks-en materia-gtk-theme neofetch neovim openssl python-pip rpmfusion-free-release rpmfusion-nonfree-release steam-devices xdotool xinput
                            xmlstarlet-1.6.1-18.fc36.x86_64
             LocalPackages: logmein-hamachi-2.1.0.203-1.x86_64
```

**Additional context**
I recently moved from Kinoite 35 and there vpn worked perfectly fine.
I pinned that deployment in case something like this happened and on fresh user (i cleared configs and home data before installing silverblue) my own user before installing, kinoite 35 indeed works just fine with this vpn.

On silverblue i tried downgrading openconnect to the same version as on kinoite 35, but it still didn't work and had the same problem. 
My assumption is that something is wrong with certificates but there no errors about them, even if i place `set -x` in `csd-post.sh` (that i placed in home folder)

Also, there is `xmlstarlet` installed via overlays - this was kinda required for `csd-post.sh` script, it has fallback to use it without `xmlstarlet` but it also says that it might not work without it
