### ISSUE TITLE
[BUG] 36.20220514.0 missing matching i686 packages?

### ISSUE THREAD

**Issue by wenottingham** [fedora-silverblue/issue-tracker#277]
**Describe the bug**
System was originally installed as SB 34, has been upgraded to SB 35, and then to SB36 (preview) last week.

Doing an upgrade today:
```
[notting@nostromo: ~]$ sudo rpm-ostree upgrade
2 metadata, 0 content objects fetched; 788 B transferred in 1 seconds; 0 bytes content written
Checking out tree 37a0304... done
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora rpmfusion-nonfree-nvidia-driver rpmfusion-nonfree-steam rpmfusion-nonfree rpmfusion-free updates-archive
Updating metadata for 'fedora-cisco-openh264'... done
Updating metadata for 'fedora-modular'... done
Updating metadata for 'updates-modular'... done
Updating metadata for 'updates'... done
Updating metadata for 'fedora'... done
Updating metadata for 'rpmfusion-nonfree-nvidia-driver'... done
Updating metadata for 'rpmfusion-nonfree-steam'... done
Updating metadata for 'rpmfusion-nonfree'... done
Updating metadata for 'rpmfusion-free'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264'; generated: 2022-04-07T16:52:38Z solvables: 4
rpm-md repo 'fedora-modular'; generated: 2022-05-04T21:12:01Z solvables: 825
rpm-md repo 'updates-modular'; generated: 2022-05-08T01:14:17Z solvables: 862
rpm-md repo 'updates'; generated: 2022-05-13T01:50:57Z solvables: 7930
rpm-md repo 'fedora'; generated: 2022-05-04T21:16:11Z solvables: 67992
rpm-md repo 'rpmfusion-nonfree-nvidia-driver'; generated: 2022-05-13T09:29:28Z solvables: 29
rpm-md repo 'rpmfusion-nonfree-steam'; generated: 2022-02-13T17:48:12Z solvables: 2
rpm-md repo 'rpmfusion-nonfree'; generated: 2022-05-04T05:11:55Z solvables: 225
rpm-md repo 'rpmfusion-free'; generated: 2022-05-04T04:48:11Z solvables: 506
rpm-md repo 'updates-archive'; generated: 2022-05-12T20:41:38Z solvables: 6914
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: package mfcl3770cdwpdrv-1.0.2-0.i386 requires libm.so.6, but none of the providers can be installed
  - package mfcl3770cdwpdrv-1.0.2-0.i386 requires libm.so.6(GLIBC_2.0), but none of the providers can be installed
  - package mfcl3770cdwpdrv-1.0.2-0.i386 requires libc.so.6(GLIBC_2.3), but none of the providers can be installed
  - package mfcl3770cdwpdrv-1.0.2-0.i386 requires libc.so.6, but none of the providers can be installed
  - package mfcl3770cdwpdrv-1.0.2-0.i386 requires libc.so.6(GLIBC_2.0), but none of the providers can be installed
  - package mfcl3770cdwpdrv-1.0.2-0.i386 requires libc.so.6(GLIBC_2.1), but none of the providers can be installed
  - glibc-2.35-5.fc36.i686 has inferior architecture
  - glibc-2.35-4.fc36.i686 has inferior architecture
  - cannot install both glibc-2.35-5.fc36.x86_64 and glibc-2.35-6.fc36.x86_64
  - cannot install both glibc-2.35-4.fc36.x86_64 and glibc-2.35-6.fc36.x86_64
  - conflicting requests
```

Printer driver package (mfcl3770cdwpdrv) hasn't been an issue for upgrades before - did the i686 glibc packages not get pushed right to the compose alongside the x86_64 ones?

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. have SB36 preview installed with an i686 layered package
2.attempt to upgrade to 36.20220514.0

**Expected behavior**
Works

**OS version:**
```
[notting@nostromo: ~]$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220510.0 (2022-05-10T01:28:36Z)
                BaseCommit: 8e68c41bf30c73f76be8da7d1fd3be18d63ce33379ecf5c4267a5b42c20d9d74
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
       RemovedBasePackages: firefox 100.0-2.fc36
           LayeredPackages: joe
             LocalPackages: mfcl3770cdwpdrv-1.0.2-0.i386
```
