### ISSUE TITLE
[BUG] Some dnf repos break GNOME Software

### ISSUE THREAD

**Issue by 1player** [fedora-silverblue/issue-tracker#295]
See also #257 which has been closed for some reason.

**Describe the bug**

Repo files with `repo_gpgcheck=1` break GNOME Software, which stops listing any application.

gnome-software shows this error message:

```
10:23:06:0595 Gs  Failed to get system: Failed to refine '*/*/*/system/*': failed to obtain lock 'metadata': Failed to create file “/var/run/dnf-metadata.lock.ZKF1M1”: Permission denied
10:23:06:0842 Gs  failed to get installed apps: failed to obtain lock 'metadata': Failed to create file “/var/run/dnf-metadata.lock.9K8XM1”: Permission denied
```

**To Reproduce**

1. cd /etc/yum.repos.d
2. curl -O https://pkgs.tailscale.com/stable/fedora/tailscale.repo
3. pkill gnome-software; gnome-software

**Expected behavior**

GNOME Software to keep working like it does on Fedora Workstation. This is a Silverblue-specific bug.

**OS version:** 
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220607.0 (2022-06-07T02:01:51Z)
          BootedBaseCommit: 7e15d96ea99c61f71bb6f9ec3c664eb92c38917c4b0cbd4669fe49985a163c41
                    Commit: 9a28071f420fe6bdbb5855a4c2fc4a81a966eef191a5a3017952fce7262d59f4
                LiveCommit: 1b65ec0a053aded4947484c80e9132dcd1fb90fbf2a288b1927a01f38a7c1e0e
                  LiveDiff: 2 added
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: distrobox liquidctl steam-devices tailscale vim zsh
             LocalPackages: rpmfusion-free-release-36-1.noarch
                            rpmfusion-nonfree-release-36-1.noarch
                            wezterm-20220605_223126_4776c8d9-1.fc36.x86_64
                  Unlocked: transient
```

**Additional context**

Removing the repo file or disable `repo_gpgcheck` fixes it.
