### ISSUE TITLE
[BUG] GNOME Software doesn't list all Flatpak results

### ISSUE THREAD

**Issue by 1player** [fedora-silverblue/issue-tracker#296]
**Describe the bug**

There are some Flatpak that can't be searched and thus can't be installed from GNOME software.

**To Reproduce**
1. Enable flathub
2. Search for "chromium"

**Expected behavior**

Chromium to be listed in the search results.

**Screenshots**

![image](https://user-images.githubusercontent.com/690120/172398892-7de3eb66-4d9d-482a-a61e-ff987303a4d9.png)

```
~ % flatpak search chromium
Name           Description                                   Application ID                Version         Branch Remotes
Chromium Web … The web browser from Chromium project         org.chromium.Chromium         87.0.4280.88    beta   flathub-beta
Chromium Web … The web browser from Chromium project         org.chromium.Chromium         102.0.5005.61   stable flathub
ungoogled-chr… A lightweight approach to removing Google we… …ub.Eloston.UngoogledChromium 88.0.4324.183   beta   flathub-beta
Chromium B.S.… Fast paced, arcade-style, top-scrolling spac… net.sourceforge.chromium-bsu  0.9.16.1        stable flathub
ungoogled-chr… A lightweight approach to removing Google we… …ub.Eloston.UngoogledChromium 102.0.5005.61-3 stable flathub
```

**OS version:**
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.service: last run failed
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220607.0 (2022-06-07T02:01:51Z)
          BootedBaseCommit: 7e15d96ea99c61f71bb6f9ec3c664eb92c38917c4b0cbd4669fe49985a163c41
                    Commit: 9a28071f420fe6bdbb5855a4c2fc4a81a966eef191a5a3017952fce7262d59f4
                LiveCommit: 0f86777b27343651d1bc3329e73c270b2de4f9e0261dae57c40087f0ce84712b
                  LiveDiff: 38 added
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: distrobox liquidctl steam-devices tailscale vim zsh
             LocalPackages: rpmfusion-free-release-36-1.noarch rpmfusion-nonfree-release-36-1.noarch
                            wezterm-20220605_223126_4776c8d9-1.fc36.x86_64
                  Unlocked: transient
```
