### ISSUE TITLE
[BUG] runtime/org.fedoraproject.Platform/x86_64/f36 Flatpak package hash mismatch

### ISSUE THREAD

**Issue by ottop** [fedora-silverblue/issue-tracker#318]
**Describe the bug**
When trying to update the Flatpak package runtime/org.fedoraproject.Platform/x86_64/f36, an error is thrown:
`Error: fedora: manifest hash in downloaded content does not match ref runtime/org.fedoraproject.Platform/x86_64/f36`.

**To Reproduce**
Either:
1. Open The software center
2. Go to the updates tab and try to update

Or:
1. Open the terminal
2. Run flatpak update

**Expected behavior**
The package is updated.

**Screenshots**

![Screenshot from 2022-07-24 15-56-51](https://user-images.githubusercontent.com/60475104/180648030-0e93b774-941d-4c3a-9a4a-8812a00a02bf.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220724.0 (2022-07-24T00:46:41Z)
                BaseCommit: 9c188835f185b9ef75698aff61e046bfc57e2547c38cdcff5e35dd4f1729bdb9
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
       RemovedBasePackages: firefox 102.0-1.fc36
           LayeredPackages: langpacks-en libvirt-daemon-config-network libvirt-daemon-kvm
                            qemu-kvm virt-install virt-manager virt-viewer
                 Initramfs: --force-drivers '"vfio vfio-pci vfio_iommu_type1 vfio_virqfd"' 

```
