### ISSUE TITLE
GNOME Software: cannot create temporary file error

### ISSUE THREAD

**Issue by aral** [fedora-silverblue/issue-tracker#344]
**Describe the bug**

GNOME Software said I had updates. I clicked on the notification. Got a modal dialogue telling me no updates were installed. (Don’t have a screen capture of that.) Then, in the updates tab, I see a ‘cannot create temporary file’ error (see screen capture).

**To Reproduce**
n/a

**Expected behavior**

Not seeing this error.

**Screenshots**

![image](https://user-images.githubusercontent.com/41798/188383409-6aab683e-a2bc-424d-bc48-8b88d26a27fd.png)

**OS version:**
```
State: busy
Transaction: refresh-md
  Initiator: caller :1.106
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.1.5 (2022-05-04T18:42:06Z)
                BaseCommit: 16ec3d1166e5281e2deb1beee62e037777bf2d013f82165adf71b7885c5a53f0
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: ffmpeg fish gnome-tweak-tool gstreamer1-plugin-openh264 langpacks-en mozilla-openh264 wireguard-tools
                            wl-clipboard
```

**Additional context**
n/a
