### ISSUE TITLE
Some images don't open

### ISSUE THREAD

**Issue by daudix-UFO** [fedora-silverblue/issue-tracker#347]
**Describe the bug**

After an update I can't open some of my SVG, PNG, JPG and other images with EOG or set them as background, there also no thumbnails in nautilus

**To Reproduce**

1. Open EOG (Fedora Flatpak)
2. Open a picture (this one as example)

![circuit](https://user-images.githubusercontent.com/77155297/190277907-ee5708c2-409b-4f8d-8c21-a20ec1c4ee38.jpg)

**Expected behavior**

A picture to open normally

**Screenshots**

![image](https://user-images.githubusercontent.com/77155297/190277937-9110c7cd-cb95-436f-970a-78bdb4b4173d.png)

![image](https://user-images.githubusercontent.com/77155297/190280025-ee09c7a2-12f0-4247-8ff0-448b412f22ec.png)

![image](https://user-images.githubusercontent.com/77155297/190279329-19dc55f3-16f1-4bf0-8a3f-21815f31d3b5.png)

![image](https://user-images.githubusercontent.com/77155297/190279540-908113a9-9bfc-4dc8-8668-0103e13f5873.png)

**OS version: 36**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20220914.0 (2022-09-14T00:52:31Z)
               BaseCommit: a7ef77686f7e30832f54d109d1f157d719a9646bb72d8a4fbec0ca7acfecc720
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
          LayeredPackages: broadcom-wl dconf-editor fish gnome-backgrounds-extras
                           gnome-console gnome-tweaks syncthing
            LocalPackages: rpmfusion-free-release-36-1.noarch
                           rpmfusion-nonfree-release-36-1.noarch
```

**Additional context**

This also happens on Workstation

_I'm sorry if this is not silverblue issue_
