### ISSUE TITLE
If firefox is removed in Silverblue36 is not possible to rebase to Silverblue37

### ISSUE THREAD

**Issue by gspe** [fedora-silverblue/issue-tracker#350]
**Describe the bug**
If firefox is removed in Silverblue36 is not possible to rebase to Silverblue37.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. rpm-ostree override remove firefox
2. reboot
3. rpm-ostree rebase fedora:fedora/37/x86_64/silverblue

**Expected behavior**
Fedora Silverblue will rebase to Silverblue 37

**Screenshots**
```
rpm-ostree rebase fedora:fedora/37/x86_64/silverblue
⠁ Receiving objects; 99% (24815/24962) 13,9 MB/s 1,1 GB                                                                                                  3521 metadata, 21441 content objects fetched; 1075708 KiB transferred in 83 seconds; 2,7 GB content written
Receiving objects; 99% (24815/24962) 13,9 MB/s 1,1 GB... done
Checking out tree 3c0e912... done
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora phracek-PyCharm rpmfusion-nonfree-nvidia-driver rpmfusion-nonfree-steam google-chrome updates-archive
Updating metadata for 'fedora-cisco-openh264'... done
Updating metadata for 'fedora-modular'... done
Updating metadata for 'updates-modular'... done
Updating metadata for 'updates'... done
Updating metadata for 'fedora'... done
Updating metadata for 'phracek-PyCharm'... done
Updating metadata for 'rpmfusion-nonfree-nvidia-driver'... done
Updating metadata for 'rpmfusion-nonfree-steam'... done
Updating metadata for 'google-chrome'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264'; generated: 2022-08-26T07:01:43Z solvables: 4
rpm-md repo 'fedora-modular'; generated: 2022-09-15T10:14:09Z solvables: 1437
rpm-md repo 'updates-modular'; generated: 2022-08-09T18:08:16Z solvables: 0
rpm-md repo 'updates'; generated: 2022-08-09T18:08:15Z solvables: 0
rpm-md repo 'fedora'; generated: 2022-09-15T10:21:10Z solvables: 67354
rpm-md repo 'phracek-PyCharm'; generated: 2022-08-24T04:55:31Z solvables: 5
rpm-md repo 'rpmfusion-nonfree-nvidia-driver'; generated: 2022-08-24T16:15:47Z solvables: 29
rpm-md repo 'rpmfusion-nonfree-steam'; generated: 2022-08-24T16:15:54Z solvables: 2
rpm-md repo 'google-chrome'; generated: 2022-09-15T15:17:10Z solvables: 3
rpm-md repo 'updates-archive'; generated: 2022-02-11T15:19:10Z solvables: 0
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: package firefox-langpacks-104.0.2-1.fc37.x86_64 requires firefox = 104.0.2-1.fc37, but none of the providers can be installed
  - conflicting requests
```

```
rpm-ostree override remove firefox-langpacks
error: Package "firefox-langpacks" not found

```

**OS version:**
```
rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20220916.0 (2022-09-16T00:55:03Z)
               BaseCommit: 39c6553ee9ddb322305db3f695b2448184931cd62eac1d5be5dc7166a35fe32c
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
      RemovedBasePackages: firefox 104.0.2-1.fc36
          LayeredPackages: fish virt-manager
                   Pinned: yes

```
