### ISSUE TITLE
Updating not possible through Software anymore

### ISSUE THREAD

**Issue by Devices** [fedora-silverblue/issue-tracker#358]
**Describe the bug**
The Download button in the Updates tab of Software disappears for one second when pressing it, displaying the loading bar, then going back to displaying the Download button. Normally, Software auto-downloads the updates but only asks me to install them.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Open "Software"
2. Navigate to tab Updates
3. Press Download button

**Expected behavior**
I only expect a button for Install. Secondly, pressing Download should download the updates.

**Screenshots**
N/a

**OS version:**
```
State: busy
Transaction: upgrade (download only)
  Initiator: client(id:gnome-software dbus:1.901 unit:dbus-:1.2-org.gnome.Software@1.service uid:1000)
BootedDeployment:
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20220923.n.0 (2022-09-23T07:57:29Z)
               BaseCommit: 58ce64d1a3405b5d72d0840da30e7bc88d341f17addfe7a00bbd269c09623b73
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
          LayeredPackages: borgbackup ffmpeg-libs fish gstreamer1-plugin-openh264 mozilla-openh264 openssl
                           rpmfusion-free-release
```

**Additional context**
Logs file:

[software logs.txt](https://github.com/fedora-silverblue/issue-tracker/files/9641210/software.logs.txt)
