### ISSUE TITLE
Space bar preview on image/video from Files blinks

### ISSUE THREAD

**Issue by aral** [fedora-silverblue/issue-tracker#364]
[Screencast from 2022-10-07 10-53-08.webm](https://user-images.githubusercontent.com/41798/194527406-d70e9cf5-6b45-448d-b6c4-3294dc4e9470.webm)

## To reproduce

1. Select an image or video in Files.
2. Press space bar.

## System details

37.20221002.n.0 (2022-10-02T08:02:45Z)
GNOME Shell 43.0

**Comment by tpopela** [comment]
I'm not able to reproduce with:

```
0 $ flatpak info org.gnome.NautilusPreviewer

Sushi - Provide a facility for quickly viewing different kinds of files

          ID: org.gnome.NautilusPreviewer
         Ref: app/org.gnome.NautilusPreviewer/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 43.0
     License: GPL-2.0+
      Origin: fedora-testing
  Collection:
Installation: system
   Installed: 84,8 MB
     Runtime: org.fedoraproject.Platform/x86_64/f37
         Sdk: org.fedoraproject.Sdk/x86_64/f37

      Commit: c0b921f43dc3c261a141b799111a334c9b49ef6fa2818ea489cacade5c2753c7
     Subject: Export org.gnome.NautilusPreviewer
        Date: 2022-10-05 20:07:41 +0000
      Alt-id: b155d49bbfffee809ffbb7ff39f8dd13c3ec600b56ef542f976f43e9897d9362
```

This build is part of https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2022-cb8daa82c9 that is currently being pushed to stable and users should get it in the following days. Can you please try again when you receive a new update?
