### ISSUE TITLE
Bug: F37 Behaviour of flathub installation

### ISSUE THREAD

**Issue by dschier-wtd** [fedora-silverblue/issue-tracker#367]
**Describe the bug**

When installing Flathub via https://flatpak.org/setup/Fedora, something weird is happening. The repository is disabled, named as "Flathub Fedora Selection" and filters are applied (Steam not findable).

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Install Fedora 37 Silverblue
2. Run `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
3. Check via `flathub remotes`
4. Check via GNOME Software -> Repositories

**Expected behavior**

Flathub is enabled properly as described in https://fedoraproject.org/wiki/Changes/Filtered_Flathub_Applications

**Screenshots**

**OS version:**
```
State: busy
Transaction: refresh-md
  Initiator: client(id:gnome-software dbus:1.109 unit:app-gnome-org.gnome.Software-2092.scope uid:1000)
BootedDeployment:
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20221012.n.0 (2022-10-12T08:02:48Z)
               BaseCommit: 544c240a85ac556351e4fc9ff54a8d90154d4c34828723f280e68cc89e0bd405
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
      RemovedBasePackages: firefox firefox-langpacks 105.0.1-2.fc37 gnome-classic-session 43.0-1.fc37
~ 
```

**Additional context**

This may be related to other "Fedora filter" bugs or not:

- https://bugzilla.redhat.com/show_bug.cgi?id=2011274
