### ISSUE TITLE
NTP service: inactive, enable chronyd on fresh installation.

### ISSUE THREAD

**Issue by fastrizwaan** [fedora-silverblue/issue-tracker#464]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
After  installing Fedora Silverblue 38, chronyd is not enabled and started causing incorrect time.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. install silverblue 
2. run `timedatectl`
```
[rizvan@fedora ~]$ timedatectl 
               Local time: Wed 2023-04-26 01:32:20 IST
           Universal time: Tue 2023-04-25 20:02:20 UTC
                 RTC time: Tue 2023-04-25 20:02:19
                Time zone: Asia/Kolkata (IST, +0530)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no
[rizvan@fedora ~]$ systemctl status chronyd
○ chronyd.service - NTP client/server
     Loaded: loaded (/usr/lib/systemd/system/chronyd.service; disabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
       Docs: man:chronyd(8)
             man:chrony.conf(5)

```

**Expected behavior**
chronyd should be enabled, and running for a working NTP service.
```
systemctl enable chronyd
systemctl start chronyd
```
**Screenshots**

**OS version:**
```
[rizvan@fedora ~]$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230425.0 (2023-04-25T00:47:58Z)
               BaseCommit: f733a30d464592886dadc042feba41e0edbafb53abea2b1f8a4fabc8b30249bb
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
      RemovedBasePackages: firefox firefox-langpacks 112.0.1-1.fc38
                           libavfilter-free libavformat-free libpostproc-free libswresample-free libavutil-free libavcodec-free libswscale-free 6.0-4.fc38
          LayeredPackages: encfs ffmpeg ffmpegthumbnailer gnome-tweaks gstreamer1-plugin-openh264 langpacks-en mozilla-openh264 VirtualBox
            LocalPackages: rpmfusion-free-release-38-1.noarch rpmfusion-nonfree-release-38-1.noarch
```

**Additional context**
