### ISSUE TITLE
LUKS passphrase input not showing when using proprietary NVIDIA drivers

### ISSUE THREAD

**Issue by ghost** [fedora-silverblue/issue-tracker#477]
**Describe the bug**
The LUKS unlock input during boot does not show if the nouveau drivers are blacklisted on a PC with an nvidia GPU and the proprietary drivers installed. At first I thought that my deployment is broken, but I just entered the passphrase with the keyboard "blindly" (as in without seeing the input) and it worked.

**To Reproduce**
1. Have PC with NVidia GPU (Quadro P2200 in this case)
2. Install Silverblue with LUKS root partition encryption
3. Install nvidia driver with rpm-ostree: [troubleshoot docs](https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_using_nvidia_drivers) and [rpmfusion docs](https://rpmfusion.org/Howto/NVIDIA#Current_GeForce.2FQuadro.2FTesla). I specifically installed every related package that rpm-ostree found then applied `kargs --append=rd.driver.blacklist=nouveau --append=modprobe.blacklist=nouveau --append=nvidia-drm.modeset=1`.
4. Reboot

**Expected behavior**
I should see the text input for the decryption password like before.

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230628.0 (2023-06-28T00:42:50Z)
               BaseCommit: f3933b350390ee28c919dc4d5824682b8391a9e4deb56d767d02fcee18a3a9f9
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
      RemovedBasePackages: firefox firefox-langpacks 114.0.2-1.fc38 gnome-terminal-nautilus gnome-terminal 3.48.1-1.fc38
          LayeredPackages: akmod-nvidia distrobox gnome-tweaks hwinfo kmod-nvidia langpacks-en libva-utils lshw lsscsi
                           nvidia-vaapi-driver podman-compose terminator vdpauinfo xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda
                           xorg-x11-drv-nvidia-cuda-libs
```

**Additional context**
Initially I just tried the instructions from the troubleshooting page, but I rolled it back because it didn't seem to work. Maybe I could have just entered the passphrase even though I didn't see the input on the screen, unsure.
