### ISSUE TITLE
"Software Updates Failed" on Rawhide

### ISSUE THREAD

**Issue by orowith2os** [fedora-silverblue/issue-tracker#486]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
When rebasing to Rawhide, the process will execute as normal. However, upon loading the shell, GNOME Software will complain that "Software Updates Failed", but it clearly did not. 

**To Reproduce**
1. Rebase to Rawhide
2. Log in

**Expected behavior**
Software wouldn't show a notification saying "Software Updates Failed"

**Screenshots**
![image](https://github.com/fedora-silverblue/issue-tracker/assets/93224879/75cde441-d3c6-4319-9135-d8b5409476a6)
![image](https://github.com/fedora-silverblue/issue-tracker/assets/93224879/38e26b3a-69c1-4138-b28a-6101ec63bc72)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/rawhide/x86_64/silverblue
                  Version: Rawhide.20230813.n.0 (2023-08-13T05:51:38Z)
               BaseCommit: e90589964ddb1fe94ad1ad175038186ab7b7a666e2ccb141692520c1b5351ec7
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
      RemovedBasePackages: firefox firefox-langpacks 116.0.2-1.fc39
          LayeredPackages: corectrl fish gnome-tweaks langpacks-en langpacks-en_GB sysprof
                           tor valgrind
            LocalPackages: opentabletdriver-0.6.0.4-1.x86_64

```

**Additional context**
Needs testing to ensure the issue doesn't happen on F38 and F39. Also need to get logs from `journalctl`.
