### ISSUE TITLE
Fractional scaling stopped working on GDM

### ISSUE THREAD

**Issue by pesader** [fedora-silverblue/issue-tracker#496]
**Describe the bug**

Until base commit `214d961525566049d92e1f9299c88a81bc0c9a59af831b711358c13c41da43e9`, fractional scaling worked on the login screen, which is GDM (gnome-display-manager) as expected. From the next deployment onward, though, it stopped working.  

**To Reproduce**

1. Boot your computer and login to your user
2. Set a fractional scaling resolution using GNOME Settings
4. Set the same fractional scaling resolution on GDM (I recommend using [Login Manager Settings](https://flathub.org/apps/io.github.realmazharhussain.GdmSettings))
5. Log out and see that fractional scaling is not working on GDM

**Expected behavior**
Fractional scaling should keep working on GDM.

**OS version:**

This is my current deployment:
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 52min ago
Deployments:
  fedora:fedora/39/x86_64/silverblue
                  Version: 39.20230930.n.0 (2023-09-30T08:05:33Z)
               BaseCommit: d8d801dd148f55b5bb24b4e4cdd7141a41a843a6c026425bfc17d6aaab6a4770
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
                     Diff: 25 upgraded, 1 removed
          LayeredPackages: firefoxpwa gocryptfs guake intel-media-driver libavcodec-freeworld libcamera libcamera-gstreamer libcamera-ipa
                           libcamera-qcam libcamera-tools nautilus-python neovim openssl podman-remote rpmfusion-free-release
                           rpmfusion-nonfree-release seahorse-nautilus steam-devices zsh
```

This is the last deployment that GDM worked properly:

```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
  fedora:fedora/39/x86_64/silverblue
                  Version: 39.20230926.n.1 (2023-09-26T17:06:23Z)
               BaseCommit: 214d961525566049d92e1f9299c88a81bc0c9a59af831b711358c13c41da43e9
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: firefoxpwa gocryptfs guake intel-media-driver
                           libavcodec-freeworld libcamera libcamera-gstreamer libcamera-ipa
                           libcamera-qcam libcamera-tools nautilus-python neovim openssl
                           podman-remote rpmfusion-free-release rpmfusion-nonfree-release
                           seahorse-nautilus steam-devices zsh
                   Pinned: yes

```

**Additional context**

My suspicion is that this has to do with an update to mutter. Running `rpm-ostree db diff` in comparison to my current deployment I got:

```
Upgraded:
  emacs-filesystem 1:29.1-1.fc39 -> 1:29.1-2.fc39
  ethtool 2:6.4-2.fc39 -> 2:6.5-1.fc39
  firefox 117.0.1-2.fc39 -> 118.0-1.fc39
  firefox-langpacks 117.0.1-2.fc39 -> 118.0-1.fc39
  giflib 5.2.1-16.fc39 -> 5.2.1-17.fc39
  glib2 2.78.0-2.fc39 -> 2.78.0-3.fc39
  harfbuzz 8.1.1-1.fc39 -> 8.2.0-1.fc39
  harfbuzz-icu 8.1.1-1.fc39 -> 8.2.0-1.fc39
  libppd 1:2.0~rc2-3.fc39 -> 1:2.0~rc2-4.fc39
  mutter 45.0-2.fc39 -> 45.0-3.fc39
  mutter-common 45.0-2.fc39 -> 45.0-3.fc39
  ostree 2023.5-3.fc39 -> 2023.6-1.fc39
  ostree-grub2 2023.5-3.fc39 -> 2023.6-1.fc39
  ostree-libs 2023.5-3.fc39 -> 2023.6-1.fc39
  python3-pillow 10.0.0-2.fc39 -> 10.0.1-1.fc39
  python3-setuptools 67.7.2-5.fc39 -> 67.7.2-7.fc39
  python3-urllib3 1.26.16-2.fc39 -> 1.26.16-3.fc39
  python3-urllib3+socks 1.26.16-2.fc39 -> 1.26.16-3.fc39
  qt5-qtbase 5.15.10-8.fc39 -> 5.15.10-9.fc39
  qt5-qtbase-common 5.15.10-8.fc39 -> 5.15.10-9.fc39
  qt5-qtbase-gui 5.15.10-8.fc39 -> 5.15.10-9.fc39
  xdg-desktop-portal 1.18.0-1.fc39 -> 1.18.0-2.fc39
```
