### ISSUE TITLE
libpod root directory (staticdir) does not match our libpod root directory (staticdir) on `fedora:fedora/39/x86_64/kinoite 39.20231204.0`

### ISSUE THREAD

**Issue by aparatext** [fedora-silverblue/issue-tracker#514]
**Describe the bug**

After some update that presumably happened somewhere within a week, libpod had become broken on `fedora:fedora/39/x86_64/kinoite 39.20231204.0`. 

**To Reproduce**
Please describe the steps needed to reproduce the bug:

1. `podman container ls`
2. Observe error `Error: database libpod root directory (staticdir) "/home/stas/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/var/home/stas/.local/share/containers/storage/libpod": database configuration mismatch`

**Expected behavior**

A list of currently running Podman containers.

**Screenshots**

N/A

**OS version:**
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● fedora:fedora/39/x86_64/kinoite
                  Version: 39.20231204.0 (2023-12-04T01:01:26Z)
               BaseCommit: e659e64215a4e59b642795366086a7f2d1f130a046ab6d5e3186d0368fd1b64e
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: 'gcc-c++' adb alsa-lib-devel automake cmake duperemove ffmpeg-free fish gcc htop
                           jetbrains-mono-fonts-all make mozilla-openh264 podman-compose podman-docker
                           powertop systemd-devel tmux xeyes
```

**Additional context**

Caused by containers/podman#20872.
