### ISSUE TITLE
CJK Font Rendering Issues w/ Flatpak Browsers

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [fedora-silverblue/issue-tracker#534]
**Describe the bug**
On a recent version, I seem to no longer have CJK (Chinese, Japanese and Korean) fonts rendering as expected when running browsers installed via flatpak. The browsers tested so far are Firefox, Vivaldi and Chromium, of which only Chromium renders CJK characters correctly. I do remember this working previously on Silverblue with the same layered packages, but I cannot find the specific version as I don't have it pinned. 

In general, I feel that there should be more documentation focused on non-english font and input for silverblue.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Install firefox or vivaldi via flatpak and run it.
2. Go to any webpage with CJK font, you'll notice tofu characters (blank boxes, often with characters inside.) Example page of Japanese content: https://fedibird.com/@ysd/109839348470538607

**Expected behavior**
CJK font should render if cjk fonts are installed on the system.

**Screenshots**
![image](https://github.com/fedora-silverblue/issue-tracker/assets/3040352/2278ec35-e4be-4418-88fd-6371c30069ab)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.20240210.0 (2024-02-10T00:38:06Z)
               BaseCommit: 665c2eab5bdc91bb41c61961e3a0f78fee9e029241d03d74e320792cbc8a9085
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
      RemovedBasePackages: firefox firefox-langpacks 122.0-5.fc39
          LayeredPackages: ckb-next ddcutil distrobox gamescope git git-lfs gnome-shell-extension-gsconnect google-noto-sans-cjk-fonts
                           htop langpacks-en nautilus-gsconnect openssl python3-pyusb realtime-setup rocm-hip syncthing vim vim-enhanced
                           vnstat

```

**Additional context**
It could very well be that firefox is looking for a specific CJK package other than google-noto-sans-cjk-fonts. If this is the case, simply knowing which package I should install would be a good start.
