### ISSUE TITLE
slirp4netns package missing in F40 base commit

### ISSUE THREAD

**Issue by tcitworld** [fedora-silverblue/issue-tracker#547]
**Describe the bug**
I'm trying to run a specific docker container with `docker start`, which outputs this
```
Error: unable to start container "7df5ccd4631ccbfbdccafac4aec785f0088686bba5337426cf5b17c36422683b": could not find slirp4netns, the network namespace can't be configured: exec: "slirp4netns": executable file not found in $PATH
```
The `slirp4netns` package is indeed not installed in the F40 current base commit, though it was in F39
```
rpm-ostree db list 708458ed3af814de6ec901e9e04872bb83c9ed8dbedcab42fd0943badce68809 | grep slirp4netns
```
Returns nothing

```
rpm-ostree db list 8b2ab1dc8e53e928d23de9ed3be548c0338c3dec3fcb1c28b1caa0df70b35b7f | grep slirp4netns
 slirp4netns-1.2.2-1.fc39.x86_64
```
Returns the package name.

Adding `slirp4netns` as a layered package allows to run the container properly.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. docker start $container

**Expected behavior**
The package being installed and `docker start` executing

**OS version:**
```
State: idle
AutomaticUpdates: check; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240403.n.0 (2024-04-03T08:15:05Z)
               BaseCommit: 708458ed3af814de6ec901e9e04872bb83c9ed8dbedcab42fd0943badce68809
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
      RemovedBasePackages: noopenh264 0.1.0~openh264_2.4.0-1.fc40
          LayeredPackages: abrt abrt-desktop distrobox ffmpegthumbnailer fido2-tools git gnome-abrt gnome-console gnome-tweak-tool google-noto-sans-bamum-fonts gstreamer1-plugin-openh264 gstreamer1-plugins-bad-free-extras gstreamer1-vaapi htop
                           intel-media-driver langpacks-fr libavcodec-freeworld libva-intel-driver libva-utils mozilla-openh264 nextcloud-client-nautilus openh264 openssl pam-u2f pamu2fcfg pipewire-codec-aptx podman-compose podman-docker
                           rpmfusion-free-release rpmfusion-nonfree-release simple-scan smartmontools solaar teamviewer vim zsh

```
