### ISSUE TITLE
issue with gstreamer1 during update

### ISSUE THREAD

**Issue by iaacornus** [fedora-silverblue/issue-tracker#558]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
the system cant update apparently due to gstreamer dependency error, ive upgraded from f39 to f40 now experiencing this

**To Reproduce**
```
rpm-ostree upgrade
```

**Expected behavior**

**Screenshots**
```
❯ rpm-ostree upgrade
2 metadata, 0 content objects fetched; 788 B transferred in 3 seconds; 0 bytes content written
Checking out tree 110ba7a... done
Inactive requests:
  langpacks-en (already provided by langpacks-en-4.0-12.fc40.noarch)
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates rpmfusion-nonfree code updates-archive
Updating metadata for 'fedora-cisco-openh264'... done
Updating metadata for 'updates'... done
Updating metadata for 'fedora'... done
Updating metadata for 'rpmfusion-free-updates'... done
Updating metadata for 'rpmfusion-free'... done
Updating metadata for 'rpmfusion-nonfree-updates'... done
Updating metadata for 'rpmfusion-nonfree'... done
Updating metadata for 'code'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264'; generated: 2023-12-11T14:43:50Z solvables: 4
rpm-md repo 'updates'; generated: 2024-04-27T02:05:39Z solvables: 8161
rpm-md repo 'fedora'; generated: 2024-04-14T18:51:11Z solvables: 74881
rpm-md repo 'rpmfusion-free-updates'; generated: 2024-04-26T21:25:38Z solvables: 18
rpm-md repo 'rpmfusion-free'; generated: 2024-04-20T12:11:51Z solvables: 422
rpm-md repo 'rpmfusion-nonfree-updates'; generated: 2024-04-26T21:48:35Z solvables: 54
rpm-md repo 'rpmfusion-nonfree'; generated: 2024-04-20T12:18:23Z solvables: 194
rpm-md repo 'code'; generated: 2024-04-26T03:16:40Z solvables: 413
rpm-md repo 'updates-archive'; generated: 2023-10-06T17:04:49Z solvables: 0
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - package gstreamer1-plugins-bad-free-extras-1.22.9-3.fc40.i686 from fedora requires libgstbase-1.0.so.0, but none of the providers can be installed
  - package gstreamer1-plugins-bad-free-extras-1.22.9-3.fc40.i686 from fedora requires libgstreamer-1.0.so.0, but none of the providers can be installed
  - package gstreamer1-plugins-bad-free-extras-1.22.9-3.fc40.x86_64 from fedora requires gstreamer1-plugins-bad-free(x86-64) = 1.22.9-3.fc40, but none of the providers can be installed
  - gstreamer1-1.22.9-1.fc40.i686 from fedora  does not belong to a distupgrade repository
  - cannot install both gstreamer1-plugins-bad-free-1.22.9-3.fc40.x86_64 from fedora and gstreamer1-plugins-bad-free-1.22.11-1.fc40.x86_64 from @System
  - cannot install both gstreamer1-1.22.9-1.fc40.x86_64 from fedora and gstreamer1-1.22.11-1.fc40.x86_64 from @System
```

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240425.0 (2024-04-25T00:38:57Z)
               BaseCommit: b115d43a18950f23fa6fe1e2a1b76727837e4cd0bee8d6ab1e6dc1ee81ee26cc
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
      RemovedBasePackages: noopenh264 0.1.0~openh264_2.4.0-1.fc40
          LayeredPackages: breeze-cursor-theme code epson-inkjet-printer-escpr epson-inkjet-printer-escpr2 fish git gnome-tweaks gstreamer1-plugin-openh264 gstreamer1-plugins-bad-free-extras
                           gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly gstreamer1-vaapi intel-media-driver libreoffice mozilla-openh264 okular papirus-icon-theme pymol
                           rpmfusion-free-release rpmfusion-nonfree-release xournalpp
            LocalPackages: epson-inkjet-printer-201401w-1.0.0-1lsb3.2.x86_64
                   Pinned: yes
```

**Additional context**
