### ISSUE TITLE
could not write /var/lib/setroubleshoot/setroubleshoot_database.xml

### ISSUE THREAD

**Issue by francoism90** [fedora-silverblue/issue-tracker#579]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
After upgrading to `40.20240702.1 (2024-07-02T17:28:29Z)` (`a0fb8bc3bb66cec33fe78d2c1734ec9c9400c20a1d033d2285cf62c8dfb78bf1`), I'm getting a lot of the following SELinux errors and applications crashes:

```bash
jul 04 11:31:00 desktop SetroubleshootPrivileged.py[437601]: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/selinux/targeted/active/modules'
jul 04 11:31:02 desktop setroubleshoot[437567]: could not write /var/lib/setroubleshoot/setroubleshoot_database.xml: [Errno 2] No such file or directory: '/var/lib/setroubleshoot/setroubleshoot_database.xml'
jul 04 11:30:48 desktop setroubleshoot[437567]: SELinux is preventing code from using the execheap access on a process. For complete SELinux messages run: sealert -l c66b45f6-31a2-4d5a-a764-3bf39f2a9fcf
```

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Upgrade to latest image
2. Reboot

**Expected behavior**
See messages.

**Screenshots**

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240702.1 (2024-07-02T17:28:29Z)
               BaseCommit: a0fb8bc3bb66cec33fe78d2c1734ec9c9400c20a1d033d2285cf62c8dfb78bf1
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
          LayeredPackages: btrfsmaintenance cockpit-kdump cockpit-networkmanager cockpit-ostree cockpit-podman cockpit-selinux cockpit-sosreport cockpit-storaged cockpit-system
                           fish gnome-tweak-tool google-roboto-fonts gstreamer1-plugin-openh264 gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly ibm-plex-mono-fonts
                           ibm-plex-sans-fonts ibm-plex-serif-fonts openssl rsms-inter-fonts tmux
            LocalPackages: rpmfusion-free-release-40-1.noarch rpmfusion-nonfree-release-40-1.noarch
```

**Additional context**
Could this be an issue with cockpit?
