### ISSUE TITLE
error when fedora-packager is layered: While applying overrides for pkg mock-core-configs: Could not find group 'mock' in group file

### ISSUE THREAD

**Issue by Zlopez** [fedora-silverblue/issue-tracker#593]
**Describe the bug**
After layering `fedora-packager` package every `rpm-ostree upgrade` fails with `error: While applying overrides for pkg mock-core-configs: Could not find group 'mock' in group file`

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. `rpm-ostree install fedora-packager`
2. `rpm-ostree upgrade`

**Expected behavior**
Update is applied

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240403.n.0 (2024-04-03T08:15:05Z)
               BaseCommit: 708458ed3af814de6ec901e9e04872bb83c9ed8dbedcab42fd0943badce68809
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
          LayeredPackages: ansible distrobox emacs fedora-packager fish flatpak-builder gnome-shell-extension-appindicator inotify-tools libvirt-client nextcloud-client
                           podman-compose podman-docker powerline powerline-fonts tmux tmux-powerline vagrant vagrant-hostmanager vagrant-sshfs vim vim-enhanced
                           vim-powerline
            LocalPackages: redhat-internal-cert-install-0.1-29.el7.noarch redhat-internal-NetworkManager-openvpn-profiles-0.1-59.el7.noarch
```

**Additional context**
I noticed that yesterday after few months as you can see from the version (I noticed that after Gnome Software notified me about vulnerability update). To update I needed to do:

1. `rpm-ostree uninstall fedora-packager`
2. `rpm-ostree upgrade`

And this is my current deployment when reporting the bug:
```
State: idle
Deployments:
  fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240904.0 (2024-09-04T02:12:02Z)
               BaseCommit: d516f5b47a48e18e2317f9f038656363384b0b880bf9d48cd9686991bb3a8a2d
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
            SecAdvisories: 2 unknown severity, 10 low, 18 moderate, 6 important, 1 critical
                     Diff: 857 upgraded, 125 removed, 23 added
          LayeredPackages: ansible distrobox emacs fish flatpak-builder gnome-shell-extension-appindicator inotify-tools libvirt-client nextcloud-client podman-compose
                           podman-docker powerline powerline-fonts tmux tmux-powerline vagrant vagrant-hostmanager vagrant-sshfs vim vim-enhanced vim-powerline
            LocalPackages: redhat-internal-cert-install-0.1-29.el7.noarch redhat-internal-NetworkManager-openvpn-profiles-0.1-59.el7.noarch
```
