### ISSUE TITLE
systemd-remount-fs.service : mount: /: fsconfig system call failed: overlay: No changes allowed in reconfigure.

### ISSUE THREAD

**Issue by TheGreatDeadOne** [fedora-silverblue/issue-tracker#605]
**Describe the bug**

Hello, I'm testing the unofficial image of SB with `bootc` and I noticed something strange in the status of systemd. The `systemd-omount-fs.service` fails to mount / (!?), But it still does not lake the operation of the OS. I should add that I tested some sysext images (I used using `mkosi` and `dnf --installroot`), following Flatcar and Fedora-Sysext's recipe, but I can't say that the error came up after the image was mounted because I only checked the loading failure Unit soon after performing `systemd-sysext unmerge`.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. systemctl status
2. service failed

**Screenshots**

![Captura de tela de 2024-10-13 23-54-49](https://github.com/user-attachments/assets/3f9c7962-667e-4955-861d-14c33b8fc926)

dmesg:

```
[   10.785509] systemd[1]: systemd-remount-fs.service: Main process exited, code=exited, status=1/FAILURE

```

**OS version:**
```
State: idle
BootedDeployment:
● ostree-unverified-registry:quay.io/fedora-ostree-desktops/silverblue:rawhide
                   Digest: sha256:647a6450a8405017f63596c081416a4d4609b1d44ce45bbcde9803e7259b4614
                  Version: 42.20241014.0 (2024-10-14T01:14:03Z)

```
bootc status

```
apiVersion: org.containers.bootc/v1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: quay.io/fedora-ostree-desktops/silverblue:rawhide
    transport: registry
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: quay.io/fedora-ostree-desktops/silverblue:rawhide
        transport: registry
      version: 42.20241014.0
      timestamp: null
      imageDigest: sha256:647a6450a8405017f63596c081416a4d4609b1d44ce45bbcde9803e7259b4614
    cachedUpdate: null
    incompatible: false
    pinned: false
    store: ostreeContainer
    ostree:
      checksum: 9f2ac59fac0fc7df9d1e74ff4d76b236f50af80f233fa3f96a36bb12a051cead
      deploySerial: 0
  rollback:
    image: null
    cachedUpdate: null
    incompatible: false
    pinned: true
    store: null
    ostree:
      checksum: 72d19057a29cd39983644bcc0422028740e79b65d8a739c06cf7a64d4575ec9a
      deploySerial: 0
  rollbackQueued: false
  type: bootcHost

```
