### ISSUE TITLE
Silverblue/ostree does not upgrade to latest stable kernel (6.12.14)

### ISSUE THREAD

**Issue by rscm** [fedora-silverblue/issue-tracker#622]
**Describe the bug**
The latest stable kernel is out (6.12.14) and even though the package is in the update servers, doing `rpm-ostree upgrade` does nothing (`No upgrade available`)

```
❯ rpm-ostree upgrade 
2 metadata, 0 content objects fetched; 788 B transferred in 3 seconds; 0 bytes content written
Checking out tree 9abe6f5... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates rpmfusion-nonfree copr:copr.fedorainfracloud.org:atim:starship copr:copr.fedorainfracloud.org:petrb:xboxdrv tailscale-stable ookla_speedtest-cli updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2024-03-11T19:22:31Z solvables: 3
rpm-md repo 'updates' (cached); generated: 2024-12-16T02:12:16Z solvables: 13766
rpm-md repo 'fedora' (cached); generated: 2024-10-24T13:55:59Z solvables: 76624
rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2024-12-12T21:02:02Z solvables: 51
rpm-md repo 'rpmfusion-free' (cached); generated: 2024-10-27T07:49:25Z solvables: 347
rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2024-12-12T21:15:58Z solvables: 27
rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2024-10-27T07:58:23Z solvables: 218
rpm-md repo 'copr:copr.fedorainfracloud.org:atim:starship' (cached); generated: 2024-12-11T08:41:50Z solvables: 2
rpm-md repo 'copr:copr.fedorainfracloud.org:petrb:xboxdrv' (cached); generated: 2024-10-24T16:48:14Z solvables: 2
rpm-md repo 'tailscale-stable' (cached); generated: 2024-12-11T17:32:29Z solvables: 115
rpm-md repo 'ookla_speedtest-cli' (cached); generated: 2021-03-31T23:23:01Z solvables: 0
rpm-md repo 'updates-archive' (cached); generated: 2024-12-16T02:54:59Z solvables: 16407
Resolving dependencies... done
No upgrade available.
```

Checking with distrobox
```
[rscm@Fedora41 ~]$ dnf list kernel*
Updating and loading repositories:
Repositories loaded.
Installed packages
kernel-headers.x86_64                6.12.4-200.fc41 updates
kernel-srpm-macros.noarch            1.0-24.fc41     fedora

Available packages
kernel.x86_64                        6.12.4-200.fc41 updates
kernel-core.x86_64                   6.12.4-200.fc41 updates
kernel-cross-headers.x86_64          6.12.4-200.fc41 updates
kernel-debug.x86_64                  6.12.4-200.fc41 updates
kernel-debug-core.x86_64             6.12.4-200.fc41 updates
kernel-debug-devel.x86_64            6.12.4-200.fc41 updates
kernel-debug-devel-matched.x86_64    6.12.4-200.fc41 updates
kernel-debug-modules.x86_64          6.12.4-200.fc41 updates
kernel-debug-modules-core.x86_64     6.12.4-200.fc41 updates
kernel-debug-modules-extra.x86_64    6.12.4-200.fc41 updates
kernel-debug-modules-internal.x86_64 6.12.4-200.fc41 updates
kernel-debug-uki-virt.x86_64         6.12.4-200.fc41 updates
kernel-debug-uki-virt-addons.x86_64  6.12.4-200.fc41 updates
kernel-devel.x86_64                  6.12.4-200.fc41 updates
kernel-devel-matched.x86_64          6.12.4-200.fc41 updates
kernel-doc.noarch                    6.12.4-200.fc41 updates
kernel-headers.i686                  6.11.3-300.fc41 fedora
kernel-modules.x86_64                6.12.4-200.fc41 updates
kernel-modules-core.x86_64           6.12.4-200.fc41 updates
kernel-modules-extra.x86_64          6.12.4-200.fc41 updates
kernel-modules-internal.x86_64       6.12.4-200.fc41 updates
kernel-rpm-macros.noarch             205-24.fc41     fedora
kernel-selftests-internal.x86_64     6.12.4-200.fc41 updates
kernel-tools.x86_64                  6.12.4-200.fc41 updates
kernel-tools-libs.x86_64             6.12.4-200.fc41 updates
kernel-tools-libs-devel.x86_64       6.12.4-200.fc41 updates
kernel-uki-virt.x86_64               6.12.4-200.fc41 updates
kernel-uki-virt-addons.x86_64        6.12.4-200.fc41 updates
kernelshark.x86_64                   1:2.3.1-4.fc41  fedora

```

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. `rpm-ostree upgrade`
2. `No upgrade available`

**Expected behavior**
`[...] Upgrades: .... kernel-6.12.4-200.fc41.x86_64.rpm .... Reboot to load the new system`

**OS version:**
Fedora Silverblue 41
```
State: idle
BootedDeployment:
● fedora:fedora/41/x86_64/silverblue
                  Version: 41.20241215.0 (2024-12-15T00:42:16Z)
               BaseCommit: 9abe6f5e524c3663ac21ee166e892b2366801308791f8d3316e301dc693bb897
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
      RemovedBasePackages: firefox firefox-langpacks 133.0.3-1.fc41 wpa_supplicant 1:2.11-3.fc41
          LayeredPackages: akmod-nvidia android-tools distrobox gnome-tweaks gparted iwd kitty printer-driver-brlaser rpmfusion-free-release rpmfusion-nonfree-release starship steam-devices tailscale vulkan-tools
                           xboxdrv xorg-x11-drv-nvidia
            LocalPackages: akmod-openrazer-100.0.0.git.588.1d12f502-1.fc41.x86_64 kmod-openrazer-100.0.0.git.588.1d12f502-1.fc41.x86_64 openrazer-kmod-common-100.0.0.git.588.1d12f502-1.fc41.x86_64
```

**Additional context**
You might say some servers are not populated yet, but three things:
 - It has been marked as stable 18 hours ago
 - The package is in the repo (4 hours, ago if you read the file metadata)
 - Just in case the system didn't used one of the top mirrors for me, I hardcoded the update server in the repo file and nothing

---

```
❯ curl -I http://fedora.c3sl.ufpr.br/linux/updates/41/Everything/x86_64/Packages/k/kernel-6.12.4-200.fc41.x86_64.rpm
HTTP/1.1 200 OK
Date: Mon, 16 Dec 2024 22:24:25 GMT
Server: Apache
Last-Modified: Wed, 11 Dec 2024 14:49:08 GMT
ETag: "2fad9-628ffb32d5d0a"
Accept-Ranges: bytes
Content-Length: 195289
Content-Type: application/octet-stream
```

```
❯ curl -I https://volico.mm.fcix.net/fedora/linux/updates/41/Everything/x86_64/Packages/k/kernel-6.12.4-200.fc41.x86_64.rpm
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Mon, 16 Dec 2024 22:25:09 GMT
Content-Type: application/x-redhat-package-manager
Content-Length: 195289
Last-Modified: Wed, 11 Dec 2024 14:49:08 GMT
Connection: keep-alive
ETag: "6759a664-2fad9"
Accept-Ranges: bytes
```
