### ISSUE TITLE
All updates will fail if using an OpenCL package

### ISSUE THREAD

**Issue by RobotRoss** [fedora-silverblue/issue-tracker#630]
**Describe the bug**
If any OpenCL packages are installed, rpm-ostree will fail to complete any and all updates due to conflicts in packages `OpenCL-ICD-Loader` and `ocl-icd` . This also means that on fresh installs, no OpenCL components can be installed, failing with a "could not depsolve transaction" error, naming the 2 packages above.

Removing some base system packages allows the installation of the ocl-icd package seemingly (possibly erroneously) required by OpenCL packages (ocl-icd and OpenCL-ICD-Loader both perform the exact same function) using the following command, however this breaks the system ffmpeg install which cannot be unbroken unless OpenCL is removed - 
```
rpm-ostree override remove libavutil-free libswscale-free libavfilter-free ffmpeg-free libavdevice-free libswresample-free gstreamer1-plugin-libav libpostproc-free libchromaprint libavformat-free libavcodec-free
rpm-ostree override replace --from-repo='fedora' --experimental --remove=OpenCL-ICD-Loader ocl-icd
```

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Attempt to install an OpenCL package, such as `mesa-libOpenCL` or `rocm-opencl` via rpm-ostree

**Expected behavior**
Packages should be able to be installed.

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/41/x86_64/silverblue
                  Version: 41.20250215.0 (2025-02-15T00:46:59Z)
               BaseCommit: 598d2e0547953271c6594b2389b805dcf7aac654b35b354c01c9731ed333306b
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
      RemovedBasePackages: gstreamer1-plugin-libav 1.24.11-1.fc41 libavdevice-free libavfilter-free libavformat-free ffmpeg-free libpostproc-free libavutil-free libavcodec-free libswresample-free libswscale-free 7.1-1.fc41
                           libchromaprint 1.5.1-24.fc41 OpenCL-ICD-Loader 3.0.6-1.20241023git5907ac1.fc41
          LayeredPackages: flatpak-builder gdb gnome-tweaks goverlay input-remapper langpacks-en_GB libxcrypt-compat mangohud mesa-libOpenCL python3-qt5 rocm-opencl spirv-llvm-translator steam-devices
            LocalPackages: lact-libadwaita-0.5.3-0.x86_64

```

**Additional context**
Problem appeared a couple of months ago (in December) when OpenCL-ICD-Loader package was added to repos.
