### ISSUE TITLE
Can't upgrade to kernel 6.13 with Nvidia drivers from rpm-fusion

### ISSUE THREAD

**Issue by rscm** [fedora-silverblue/issue-tracker#632]
**Describe the bug**
I'm not able to get the new kernel and new nvidia drivers built by running `rpm-ostree upgrade`

possible duplicates: #286 

This is the output
```
❯ rpm-ostree upgrade 
⠚ Receiving metadata objects: 1/(estimating) 98 bytes/s 196 bytes...                                                                                                                                                 2 metadata, 0 content objects fetched; 788 B transferred in 2 seconds; 0 bytes content written
Receiving metadata objects: 1/(estimating) 98 bytes/s 196 bytes... done
Checking out tree 0e2ab47... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora rpmfusion-free-tainted rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-tainted rpmfusion-nonfree-updates rpmfusion-nonfree copr:copr.fedorainfracloud.org:atim:starship copr:copr.fedorainfracloud.org:petrb:xboxdrv tailscale-stable ookla_speedtest-cli updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2024-03-11T19:22:31Z solvables: 3
rpm-md repo 'updates' (cached); generated: 2025-02-26T01:09:41Z solvables: 21552
rpm-md repo 'fedora' (cached); generated: 2024-10-24T13:55:59Z solvables: 76624
rpm-md repo 'rpmfusion-free-tainted' (cached); generated: 2025-02-26T15:40:43Z solvables: 5
rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2025-02-21T11:02:14Z solvables: 87
rpm-md repo 'rpmfusion-free' (cached); generated: 2024-10-27T07:49:25Z solvables: 347
rpm-md repo 'rpmfusion-nonfree-tainted' (cached); generated: 2025-02-06T20:24:10Z solvables: 6
rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2025-02-21T11:29:36Z solvables: 53
rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2024-10-27T07:58:23Z solvables: 218
rpm-md repo 'copr:copr.fedorainfracloud.org:atim:starship' (cached); generated: 2025-01-12T07:49:18Z solvables: 2
rpm-md repo 'copr:copr.fedorainfracloud.org:petrb:xboxdrv' (cached); generated: 2024-10-24T16:48:14Z solvables: 2
rpm-md repo 'tailscale-stable' (cached); generated: 2025-02-24T04:08:58Z solvables: 117
rpm-md repo 'ookla_speedtest-cli' (cached); generated: 2021-03-31T23:23:01Z solvables: 0
rpm-md repo 'updates-archive' (cached); generated: 2025-02-26T01:39:55Z solvables: 34093
Resolving dependencies... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
error: Running %post for akmod-nvidia: bwrap(/bin/sh): El proceso hijo terminado por la señal 1; run `journalctl -t 'rpm-ostree(akmod-nvidia.post)'` for more information

```

I ran the command with sudo too, just in case

journalctl output (txt >90Mb):
[kernel_6.13_akmod-nvidia.zip](https://github.com/user-attachments/files/18996322/kernel_6.13_akmod-nvidia.zip)

journalctl output with sudo (txt >90Mb):
[kernel_6.13_akmod-nvidia-w_sudo.zip](https://github.com/user-attachments/files/18996360/kernel_6.13_akmod-nvidia-w_sudo.zip)

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Have a running Silverblue system with the kernel `6.12.15-200.fc41.x86_64` and proprietary nvidia drivers from rpm-fusion version `565.77`
2. run `rpm-ostree upgrade`

**Expected behavior**
- A new composed system image built ready to boot on after a restart containing the new kernel v6.13 and new nvidia drivers v570

**OS version:**
```
❯ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/41/x86_64/silverblue
                  Version: 41.20250220.0 (2025-02-20T00:49:01Z)
               BaseCommit: bb03e0d47b4de7ffa617903310ed5c7e73356e6688542e3ef1f3d782feba74ed
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
          LayeredPackages: akmod-nvidia android-tools distrobox gnome-tweaks gparted kitty printer-driver-brlaser rpmfusion-free-release rpmfusion-free-release-tainted rpmfusion-nonfree-release
                           rpmfusion-nonfree-release-tainted starship steam-devices tailscale vulkan-tools xboxdrv xorg-x11-drv-nvidia-cuda
            LocalPackages: akmod-openrazer-100.0.0.git.588.1d12f502-1.fc41.x86_64 kmod-openrazer-100.0.0.git.588.1d12f502-1.fc41.x86_64 openrazer-kmod-common-100.0.0.git.588.1d12f502-1.fc41.x86_64
```

**Additional context**
I looked for a similar issue and found this bug report
https://bugzilla.rpmfusion.org/show_bug.cgi?id=6317

- In it the OP says that limiting threads down to 8 worked for him, I tried it and didn't worked
- Also another person wrote about file limit set too low (on comment  5), I changed that too and nothing

---

I did tried resetting the deployment, getting everything (inc. kernel 6.13) but the nvidia drivers. And then it failed with the same error when I tried to install the Nvidia drivers
